USE [master]
GO

/****** Object:  Database [OtmDataBase]    Script Date: 21/01/2023 15:22:48 ******/
CREATE DATABASE [OtmDataBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OtmDataBase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\OtmDataBase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OtmDataBase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\OtmDataBase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OtmDataBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO


ALTER DATABASE [OtmDataBase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OtmDataBase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OtmDataBase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OtmDataBase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OtmDataBase] SET ARITHABORT OFF 
GO

ALTER DATABASE [OtmDataBase] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [OtmDataBase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OtmDataBase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OtmDataBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OtmDataBase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OtmDataBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OtmDataBase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OtmDataBase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OtmDataBase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OtmDataBase] SET  ENABLE_BROKER 
GO

ALTER DATABASE [OtmDataBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OtmDataBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OtmDataBase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OtmDataBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OtmDataBase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OtmDataBase] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [OtmDataBase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OtmDataBase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OtmDataBase] SET  MULTI_USER 
GO

ALTER DATABASE [OtmDataBase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OtmDataBase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OtmDataBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OtmDataBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OtmDataBase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OtmDataBase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [OtmDataBase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [OtmDataBase] SET  READ_WRITE 
GO


